### ISSUE TITLE
Inloggen met een account van andere verenigingen geeft 500

### ISSUE THREAD

**Issue by WKobes** [SVArago/alexia#20]
Ik probeerde met m'n s-nummer in te loggen op jullie versie van alexia, waarschijnlijk gaat het stuk omdat ik geen arago-lid ben. Als jullie mijn wachtwoord in de mailbox hebben staan hoor ik het graag ;)

**Comment by DanielVoogsgerd** [comment]
Jup we hebben hier een prachtig error report met een wachtwoord erin ;)
Misschien is het uberhaupt wel slim om een wat sterker wachtwoord te nemen voor je s-account :)

**Comment by WKobes** [comment]
touche

**Comment by oxan** [comment]
Laten we die ook niet mailen in dit soort situaties, al is het maar omdat we onze overeenkomst met ICTS over RADIUS-access daarmee overtreden. #21

**Comment by oxan** [comment]
De bug zelf is een dom non-nullable foutje zo te zien, zal ik vanavond wel even fixen.

**Comment by oxan** [comment]
Vergeten migrations te draaien bij Django update, nu gefixt.
